{
 "title": "Works Statistics",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "select 'minute' AS __text, '%Y%m%d%H%i' as __value union select 'hour' AS __text, '%Y%m%d%H' as __value union select 'day' AS __text, '%Y%m%d' as __value union select 'month' AS __text, '%Y%m' as __value"
   }
  ]
 },
 "panels": [
  {
   "title": "Error Works",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(arrivaldate) as time_sec, count(*) as value\n       from (\n         (select arrivaldate from works \n         where not isnull(arrivaldate)\n\t       \tand status=\"ERROR\")\n\t union all\n\t (select arrivaldate from works_history \n         where not isnull(arrivaldate)\n\t       \tand status=\"ERROR\")\n \t  ) as t \ngroup by arrivaldate"
    }
   ]
  },
  {
   "title": "Completed Works",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(completeddate) as time_sec, count(*) as value\n       from (\n         (select completeddate from works \n         where not isnull(completeddate)\n\t       \tand status=\"COMPLETED\")\n\t     union all\n         (select completeddate from works_history \n         where not isnull(completeddate)\n\t       \tand status=\"COMPLETED\")\n \t  ) as t \ngroup by completeddate"
    }
   ]
  },
  {
   "title": "Error Works",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select MIN(UNIX_TIMESTAMP(arrivaldate)) as time_sec, count(*) as value, 'Works' as metric\n       from (\n         (select DATE(arrivaldate) as arrivaldate from works \n         where not isnull(arrivaldate)\n\t       \tand status=\"ERROR\")\n\t union all\n\t (select DATE(arrivaldate) as arrivaldate from works_history \n         where not isnull(arrivaldate)\n\t       \tand status=\"ERROR\")\n \t  ) as t \nGROUP BY date_format(arrivaldate, \"$interval\")\nORDER BY date_format(arrivaldate, \"$interval\") ASC\n"
    }
   ]
  },
  {
   "title": "Completed Works",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select MIN(UNIX_TIMESTAMP(completeddate)) as time_sec, count(*) as value, 'Works' as metric\n       from (\n         (select completeddate from works \n         where not isnull(completeddate)\n\t       \tand status=\"COMPLETED\" and $__timeFilter(completeddate))\n\t     union all\n         (select completeddate from works_history \n         where not isnull(completeddate) and $__timeFilter(completeddate)\n\t       \tand status=\"COMPLETED\")\n \t  ) as t \nGROUP BY date_format(completeddate, \"$interval\")\nORDER BY date_format(completeddate, \"$interval\") ASC\n"
    }
   ]
  },
  {
   "title": "Started Works",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select MIN(UNIX_TIMESTAMP(laststartdate)) as time_sec, count(*) as value, 'Works' as metric\n       from (\n         (select laststartdate from tasks \n         where not isnull(laststartdate) and $__timeFilter(laststartdate))\n\t     union all\n         (select laststartdate from tasks_history \n         where not isnull(laststartdate) and $__timeFilter(laststartdate))) as t \nGROUP BY date_format(laststartdate, \"$interval\")\nORDER BY date_format(laststartdate, \"$interval\") ASC\n"
    }
   ]
  },
  {
   "title": "Restarted Works",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select MIN(UNIX_TIMESTAMP(laststartdate)) as time_sec , count(*) as value, 'Works' as metric\n       from (\n         (select laststartdate, count(*) as restarteds from tasks \n         where not isnull(laststartdate)\n \t \t\tand not isnull(startdate)\n          group by laststartdate)\n\t     union all\n         (select laststartdate, count(*) as restarteds from tasks_history\n         where not isnull(laststartdate)\n \t \t\tand not isnull(startdate)\n          group by laststartdate)\n \t  ) as t \nGROUP BY date_format(laststartdate, \"$interval\")\nORDER BY date_format(laststartdate, \"$interval\") ASC"
    }
   ]
  },
  {
   "title": "Submitted Works",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select MIN(UNIX_TIMESTAMP(arrivaldate)) as time_sec, count(*) as value, 'Works' as metric\n       from (\n         (select arrivaldate from works \n         where not isnull(arrivaldate) and $__timeFilter(arrivaldate))\n\t     union all\n         (select arrivaldate from works_history \n         where not isnull(arrivaldate) and $__timeFilter(arrivaldate))\n \t  ) as t\nGROUP BY date_format(arrivaldate, \"$interval\")\nORDER BY date_format(arrivaldate, \"$interval\") ASC\n\n"
    }
   ]
  },
  {
   "title": "Works Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select workuid, completeddate,\n       laststartdate,\n       startdate,\n       insertiondate,\n       arrivaldate,\n       run,\n       restart,\n       pending,\n       waiting\n       from (\n         (select workuid, date_format(completeddate,\"%Y/%m/%d %H:%i\") as completeddate,\n\t\t       laststartdate,\n\t\t       startdate,\n\t\t       insertiondate,\n\t\t       arrivaldate,\n\t\t       unix_timestamp(completeddate)-unix_timestamp(laststartdate) as run,\n\t\t       unix_timestamp(laststartdate)-unix_timestamp(startdate) as restart,\n\t\t       unix_timestamp(startdate)-unix_timestamp(insertiondate) as pending,\n\t\t       unix_timestamp(insertiondate)-unix_timestamp(arrivaldate) as waiting\n            from works, tasks\n            where works.uid=tasks.workuid\n\t       \t  and works.status=\"COMPLETED\" \n \t \t\t  and not isnull(completeddate))\n\t     union all\n         (select workuid, date_format(completeddate,\"%Y/%m/%d %H:%i\") as completeddate,\n\t\t       laststartdate,\n\t\t       startdate,\n\t\t       insertiondate,\n\t\t       arrivaldate,\n\t\t       unix_timestamp(completeddate)-unix_timestamp(laststartdate) as run,\n\t\t       unix_timestamp(laststartdate)-unix_timestamp(startdate) as restart,\n\t\t       unix_timestamp(startdate)-unix_timestamp(insertiondate) as pending,\n\t\t       unix_timestamp(insertiondate)-unix_timestamp(arrivaldate) as waiting\n            from works_history, tasks_history\n            where works_history.uid=tasks_history.workuid\n\t       \t  and works_history.status=\"COMPLETED\" \n \t \t\t  and not isnull(completeddate))\n \t  ) as t "
    }
   ]
  },
  {
   "title": "Users Works",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select login,nbJobs,pendingJobs,runningJobs,errorJobs from users union select login,nbJobs,pendingJobs,runningJobs,errorJobs from users_history;"
    }
   ]
  },
  {
   "title": "Workers works",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "select hosts.name as Name, hosts.uid as Uid, hosts.ipaddr as IpAddress, count(*) as Works\n       from tasks,works,hosts \n       where works.status=\"COMPLETED\" \n       \t     and works.uid=tasks.workuid\n\t     and tasks.hostuid=hosts.uid\ngroup by hosts.uid"
    }
   ]
  }
 ]
}