#!/bin/sh
#=============================================================================
#
#  File    : xwstartpdo.sh
#  Date    : November, 2018
#  Author  : Oleg Lodygensky
#
#  Change log:
#  - Nov 9th,2018 : Oleg Lodygensky; creation
#
#  OS      : Linux, mac os x
#
#  Purpose : this script starts docker for Intel PDO on worker side
#
#
#  !!!!!!!!!!!!!!!!    DO NOT EDIT    !!!!!!!!!!!!!!!!
#  Remarks : this script is auto generated by install process
#
#=============================================================================


# Copyrights     : iExec
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb-HEP by CNRS
# Web            : https://iex.ec
#
#      This file is part of XtremWeb-HEP.
#
# Copyright [2018] [iExec]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#




THISOS=`uname -s`

case "$THISOS" in

  Darwin )
    DATE_FORMAT='+%Y-%m-%d %H:%M:%S%z'
    ;;

  Linux )
    DATE_FORMAT='--rfc-3339=seconds'
    ;;

  * )
    fatal  "OS not supported ($THISOS)"  TRUE
    ;;

esac

#=============================================================================
#
#  Function  fatal (Message, Force)
#
#=============================================================================
fatal ()
{
  msg="$1"
  FORCE="$2"
  [ "$msg" ]  ||  msg="Ctrl+C"

  echo  "$(date "$DATE_FORMAT")  $SCRIPTNAME  FATAL : $msg"

  exit 1
}

#=============================================================================
#
#  Function  warning (Message)
#
#=============================================================================
warning ()
{
  msg="$1"
  echo  "$(date "$DATE_FORMAT")  $SCRIPTNAME  WARNING : $msg"
  return 0
}

#=============================================================================
#
#  Function  info (Message)
#
#=============================================================================
info ()
{
  msg="$1"
  echo  "$(date "$DATE_FORMAT")  $SCRIPTNAME  INFO : $msg"
  return 0
}

#=============================================================================
#
#  Function  debug (Message)
#
#=============================================================================
debug ()
{
  msg="$1"
  [ "${TESTINGONLY}" = "TRUE" ] && echo  "$(date "$DATE_FORMAT")  $SCRIPTNAME  DEBUG : $msg"
  return 0
}

#=============================================================================
#
#  Main
#
#=============================================================================
trap  fatal  INT  TERM


ARGS=$*

IMAGENAME="${XWDOCKERIMAGE}"
CONTAINERNAME="iexecpdo"
IEXECDIRNAME="iexec"
PDOWORKINGDIR="/tmp/pdo/${IEXECDIRNAME}"

[ -d ${PDOWORKINGDIR} ] || mkdir -p ${PDOWORKINGDIR}

#
# files will be stored in /iexec in the container
# but we must retrieve result files here
#

ln -s ${PDOWORKINGDIR} . || fatal "can't link ${PDOWORKINGDIR}"
cd ${IEXECDIRNAME}

#
# clean first
#
rm -f *

# the container must have been launched in ${PDOWORKINGDIR} using the following command
#docker run ${PDOARGS} -v ${PDOWORKINGDIR}:/iexec --rm --name ${CONTAINERNAME} --env-file ${ENVFILENAME} ${IMAGENAME} ${ARGS} 2>&1 |  grep -vE "Unable to find image|Pulling from|Pull complete|Digest:|Status:|: Pulling fs layer|: Verifying Checksum|: Download complete|: Already exists"

#docker exec  --workdir /${IEXECDIRNAME} ${CONTAINERNAME} ${ARGS} 2>&1
docker exec  ${CONTAINERNAME} ${ARGS} 2>&1

#
# we want toretrieve result files here
#
cd ..
mv ${IEXECDIRNAME}/* .
rm -Rf ${IEXECDIRNAME}


exit 0
###########################################################
#     EOF        EOF     EOF        EOF     EOF       EOF #
###########################################################
